aggregate:
- alias: avg_salary
  columns:
  - salary
  function: avg
- alias: avg_age
  columns:
  - age
  function: avg
data:
  dest: exported.csv
  src: simple.csv
mirror:
  url:
    -  https://github.com/n-dusan/exported-data-example
  strategy: tag
  token: <TOKEN>